### ISSUE TITLE
Call Tool Images

### ISSUE THREAD

**Issue by catachresis** [18mr/documentation#10]
![chu](https://cloud.githubusercontent.com/assets/2704279/8621822/908469ce-26dc-11e5-8175-e42bd401f539.PNG)

**Comment by catachresis** [comment]
![swnh](https://cloud.githubusercontent.com/assets/2704279/8622533/da46e722-26e0-11e5-8039-44e1b17887c3.PNG)

**Comment by Oanh-Nhi** [comment]
Downloaded
