### ISSUE TITLE
Move Image Storage

### ISSUE THREAD

**Issue by catachresis** [18mr/documentation#12]

**Comment by catachresis** [comment]
@Oanh-Nhi, would you be interested in taking on this task? Images in open issues need to be moved into Images directory and then pages in documentation need to be updated.

**Comment by Oanh-Nhi** [comment]
Sure just let me know how and I'll do it

On Thursday, May 5, 2016, cayden <notifications@github.com> wrote:

> @Oanh-Nhi <https://github.com/Oanh-Nhi>, would you be interested in
> taking on this task? Images in open issues need to be moved into Images
> directory and then pages in documentation need to be updated.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/18mr/documentation/issues/12#issuecomment-217286235>
>


-- 

OANH-NHI NGUYEN

*KAIROS FELLOW & DIGITAL CAMPAIGNER*

914.882.9204

oanh-nhi@18millionrising.org

18MR.org <http://www.18mr.org/>   |   Facebook
<https://www.facebook.com/18MillionRising.org>   |   Twitter
<https://twitter.com/18millionrising>   |   Tumblr <http://18mr.tumblr.com/>

**Comment by catachresis** [comment]
Basically, just download all the images that are embedded in issues, close all those issues, and re-upload them as a commit to the [images folder](https://github.com/18mr/documentation/tree/master/images). You'll have to re-embed everything in each documentation article. I'm going to give you direct edit access to this repo to make things easier.

**Comment by Oanh-Nhi** [comment]
will take a look later today!!

On Fri, May 6, 2016 at 8:00 PM, cayden <notifications@github.com> wrote:

> Basically, just download all the images that are embedded in issues, close
> all those issues, and re-upload them as a commit to the images folder
> <https://github.com/18mr/documentation/tree/master/images>. You'll have
> to re-embed everything in each documentation article. I'm going to give you
> direct edit access to this repo to make things easier.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/18mr/documentation/issues/12#issuecomment-217590208>
>



-- 

OANH-NHI NGUYEN

*KAIROS FELLOW & DIGITAL CAMPAIGNER*

914.882.9204

oanh-nhi@18millionrising.org

18MR.org <http://www.18mr.org/>   |   Facebook
<https://www.facebook.com/18MillionRising.org>   |   Twitter
<https://twitter.com/18millionrising>   |   Tumblr <http://18mr.tumblr.com/>

**Comment by catachresis** [comment]
Awesome - one more step: change the embedded images to be the ones you saved in the images folder. Thank you for helping!
