### ISSUE TITLE
Edit in GitHub

### ISSUE THREAD

**Issue by catachresis** [18mr/documentation#5]
![file](https://cloud.githubusercontent.com/assets/2704279/4512635/aacd53de-4b42-11e4-8e2f-3be0d5256c5c.PNG)

![edit](https://cloud.githubusercontent.com/assets/2704279/4512636/aad00cd2-4b42-11e4-9da2-e9a3995f24c4.PNG)

![createnew](https://cloud.githubusercontent.com/assets/2704279/4512637/aad00b06-4b42-11e4-8e24-dda7bc9d98c4.PNG)

![newpost](https://cloud.githubusercontent.com/assets/2704279/4512638/aad050e8-4b42-11e4-8101-537ded83493f.PNG)

**Comment by Oanh-Nhi** [comment]
Downloaded
