### ISSUE TITLE
Sync Your Fork

### ISSUE THREAD

**Issue by catachresis** [18mr/documentation#6]
![behind-ghpages](https://cloud.githubusercontent.com/assets/2704279/4584287/9a5d6410-4ff9-11e4-9d6a-7fb35d5b821b.PNG)
![switchbase](https://cloud.githubusercontent.com/assets/2704279/4584289/9a67c946-4ff9-11e4-801b-5a3e58efb91c.PNG)
![createpullrequest](https://cloud.githubusercontent.com/assets/2704279/4584288/9a64d0e2-4ff9-11e4-8fcd-8c4c9c8a3b55.PNG)
![pullrequests](https://cloud.githubusercontent.com/assets/2704279/4584290/9a7984d8-4ff9-11e4-8304-0a20a4cd5e9a.PNG)
![merge](https://cloud.githubusercontent.com/assets/2704279/4584291/9b3aed94-4ff9-11e4-8f93-299ca6d7a801.PNG)

**Comment by Oanh-Nhi** [comment]
Downloaded
